### ISSUE TITLE
Composer install not working for Mautic5.1 due to conflicting requirements for PHP version

### ISSUE THREAD

**Issue by dsp76** [Webmecanik/mautic-pipedrive-bundle#10]
Hi there, 
I tried to install the plugin via composer. 

When I used PHP8.1 I got this:

> Cannot use webmecanik/mautic-pipedrive-bundle's latest version 9999999-dev as it requires php >=7.4.0 <8.1 which is not satisfied by your platform.

I used PHP8.0 which started the process, but failed to resolve dependencies:

> ./composer.json has been updated
Running composer update webmecanik/mautic-pipedrive-bundle
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

>  Problem 1
    - knplabs/knp-menu-bundle v3.4.2 requires php ^8.1 -> your php version (8.0.30) does not satisfy that requirement.
    - mautic/core-lib 5.1.0 requires knplabs/knp-menu-bundle ^3.0 -> satisfiable by knplabs/knp-menu-bundle[v3.4.2].
    - mautic/core-lib is locked to version 5.1.0 and an update of this package was not requested.

> You can also try re-running composer require with an explicit version constraint, e.g. "composer require webmecanik/mautic-pipedrive-bundle:*" to figure out if any version is installable, or "composer require webmecanik/mautic-pipedrive-bundle:^2.1" if you know which you need.

**Comment by peeterma** [comment]
I am having the same issue

**Comment by kuzmany** [comment]
The plugin does not currently support M5. We will introduce a supported version soon.

**Comment by peeterma** [comment]
Any news about Mautic 5 support?

**Comment by kuzmany** [comment]
Pushed to main branch version compatible with Mautic 5 https://github.com/Webmecanik/mautic-pipedrive-bundle
