### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by ThomasRambaud** [Webmecanik/mautic-pipedrive-bundle#2]
Dear Webmecanik team,
First thanks for your good job!

I have trouble installing this new plugin. There seems to be a conflict with the MauticCrmBundle plugin, with a classname duplicated in both plugins (mautic-pipedrive-bundle and the legacy MauticCrmBundle).

I'm not using composer (neither for mautic install nor plugins). 

I created a folder named "Pipedrive2" under plugins/ with the plugin content. 
I then clicked on the button "Install/update plugins" but nothing appears.
I also tried to execute php bin/console mautic:plugins:reload and mautic:plugins:install and it also says that "0 plugins were installed or updated".

I tried removing MauticCrmBundle/ folder from the plugins/ folder. But it's not any better. The MauticCrmBundle/ seems to be still loaded from the composer/vendor repository.

![image](https://user-images.githubusercontent.com/1260302/212073416-03821faa-c6cf-4e5d-9aca-9daee8cb36e7.png)

Do you have any hint on how this plugin should be installed, which version of Mautic is it compatible with, and if MauticCrmBundle should be removed? The documentation probably lacks informations on those points.

Regards,

**Comment by kuzmany** [comment]
Plugins should installed under plugins/PipedriveBundle or by composer `composer require webmecanik/mautic-pipedrive-bundle`

There is no conflict because we create new Pipedrive2 integration and it can work along with older Pipedrive integration.
