### ISSUE TITLE
Sync triggering underfined method getInputOptionsDAO() 

### ISSUE THREAD

**Issue by joelakuhn** [Webmecanik/mautic-pipedrive-bundle#3]
I have this plugin installed. Nothing is syncing between Pipedrive and Mautic, and when I run the cron job, I get the error:

php bin/console mautic:integrations:sync Pipedrive2

`[ERROR] Call to undefined method Mautic\IntegrationsBundle\Event\SyncEvent::getInputOptionsDAO()`

**Comment by kuzmany** [comment]
We need to push PR against to Mautic repository  with these methods, I will try to look at it tomorrow

**Comment by kuzmany** [comment]
I found it's already figured out with https://github.com/mautic/mautic/pull/11255
Can you apply this PR and check If works for you?

**Comment by joelakuhn** [comment]
@kuzmany Thanks, I'll give that a shot tonight EST.

**Comment by joelakuhn** [comment]
That didn't do it, but I duplicated the `getInputOptions` method as `getInputOptionsDAO`, and it's working now.

**Comment by kuzmany** [comment]
I reopen the issue. 
I need to revert our part and then add https://github.com/mautic/mautic/pull/11255 and make changes related to that PR
Thank you for report

**Comment by kuzmany** [comment]
Ok, we've added support for https://github.com/mautic/mautic/pull/11255 with commit https://github.com/Webmecanik/mautic-pipedrive-bundle/commit/30c94e54c5f878b2935b7bcfa6cfa504e8d6b663

I'll close it and re-open once If need it
