### ISSUE TITLE
First Name and Last Name missing from contact mapping

### ISSUE THREAD

**Issue by stevedrobinson** [Webmecanik/mautic-pipedrive-bundle#6]
Everything else seems to be working perfectly, but when I configure the plugin inside of mautic, the contact field mapping is missing fields for first name and last name and when new contacts sync from pipedrive, they are missing first and last name on their records. 

![image](https://user-images.githubusercontent.com/866855/222634135-884c1b38-dbc9-4329-8df9-62917d9374a7.png)

![image](https://user-images.githubusercontent.com/866855/222634171-7dc3922b-69b2-4544-b14a-6e69a3d54d92.png)

**Comment by kuzmany** [comment]
Can you look in Pipedrive settings To enable first name and last name in API?  We are able to map it in our side

**Comment by stevedrobinson** [comment]
Got it! I didn't realize that there were first and last name fields in pipedrive that only get activated if you ask support to activate them. This should be part of the documentation. Would you like me to submit a PR, or can you just add it?

Something like, prior to installing the plugin, you must reach out to Pipedrive Support to enable first and last name fields if you have not done so already. Simply start a support chat and ask, "Could you please enable first and last name default fields?" and they will happily do so.

**Comment by npracht** [comment]
added in documentation today with https://github.com/Webmecanik/mautic-pipedrive-bundle/commit/236d79ac9510bffc80d920fcc549fb643069c923

Thanks @stevedrobinson !
