### ISSUE TITLE
installing pipedrive, which version of Mautic

### ISSUE THREAD

**Issue by raramuridesign** [Webmecanik/mautic-pipedrive-bundle#8]
@npracht @kuzmany 
I have a few questions

1. is this new plugin only available for version 5 of mautic or can this be installed on version 4?
2. installing this manually, is there a specific folder name to use, so it is recognised in Mautic?

I would appreciate a quick response on this, thanks
M.

**Comment by raramuridesign** [comment]
This is the Folder name I used, but it is not picked up in Mautic v4.4.9

![image](https://github.com/Webmecanik/mautic-pipedrive-bundle/assets/902376/575a7366-8a9b-49cb-b214-32cf18d212e6)

**Comment by raramuridesign** [comment]
@npracht Is there any chance you can provide feedback on this question.
Thanks.

**Comment by npracht** [comment]
Hello @raramuridesign !
I am very sorry, I was not notified and I didn't see the issue / messages.

You can use it in mautic 4. I invite you to process as follow:
--> https://github.com/Webmecanik/mautic-pipedrive-bundle#installation
> You can install this plugin using composer using command: composer require webmecanik/mautic-pipedrive-bundle
> Or manually from GitHub: https://github.com/webmecanik/mautic-pipedrive-bundle

On my side on our project it is installed `../plugins/PipedriveBundle`

**Comment by raramuridesign** [comment]
@npracht Thank you - appreciate the feedback.
